puts "The Students of Villians Academy"
puts "------------------------"
puts "Dr. Hannibal Lecter"
puts "Lord Vader"
puts "Nurse Ratched"
puts "Michael 'The Don' Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Jeffory Baratheon"
puts "Norman Bates"
 
